#![no_std]
#![forbid(unsafe_code)]
//! A fast, embedded word list you can index, with zero runtime init and zero
//! allocation.
//!
//! The whole list is baked into the binary at compile time, with each word's
//! start offset computed ahead of time in `build.rs`, so indexed lookup is a
//! plain slice. The list is sorted and duplicate-free, so [`position`],
//! [`contains`] and [`starting_with`] are binary searches over it.

use core::ops::{Bound, RangeBounds};

mod data {
    // Generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/worddata.rs"));
}

/// How many words there are.
pub const LEN: usize = data::WORD_COUNT;

/// Resolve a word index into the slice of the blob it borrows.
///
/// `STARTS` holds one offset per word plus a sentinel, and `build.rs` writes
/// exactly one separator byte after every word, so a word ends one byte before
/// the next one starts. Storing starts alone halves the index.
#[inline]
fn word(index: usize) -> &'static str {
    let start = data::STARTS[index] as usize;
    let end = data::STARTS[index + 1] as usize - 1;
    &data::BLOB[start..end]
}

/// Index of the first word in `lo..hi` where `pred` turns false. `pred` must
/// hold for a (possibly empty) prefix of the range and fail for the rest.
#[inline]
fn partition_point(lo: usize, hi: usize, pred: impl Fn(usize) -> bool) -> usize {
    let (mut lo, mut hi) = (lo, hi);
    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        if pred(mid) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    lo
}

#[inline]
pub fn len() -> usize {
    LEN
}

#[inline]
pub fn is_empty() -> bool {
    LEN == 0
}

/// Look up a single word by index. O(1), no allocation. Out of range is `None`.
#[inline]
pub fn get(index: usize) -> Option<&'static str> {
    if index < LEN { Some(word(index)) } else { None }
}

/// Look up a contiguous range of words as an allocation-free iterator.
///
/// Accepts any range (`a..b`, `a..=b`, `a..`, `..b`, `..`). Returns `None` if
/// the range is out of bounds or its start is past its end — matching [`get`].
///
/// ```
/// let mut it = am_wordlist::get_range(0..3).unwrap();
/// assert_eq!(it.clone().count(), 3);
/// assert_eq!(it.next(), am_wordlist::get(0));
/// assert!(am_wordlist::get_range(0..=am_wordlist::LEN).is_none());
/// ```
#[inline]
pub fn get_range<R: RangeBounds<usize>>(
    range: R,
) -> Option<impl Iterator<Item = &'static str> + Clone> {
    let start = match range.start_bound() {
        Bound::Included(&n) => n,
        Bound::Excluded(&n) => n.checked_add(1)?,
        Bound::Unbounded => 0,
    };
    let end = match range.end_bound() {
        Bound::Included(&n) => n.checked_add(1)?,
        Bound::Excluded(&n) => n,
        Bound::Unbounded => LEN,
    };
    if start > end || end > LEN {
        return None;
    }
    Some((start..end).map(word as fn(usize) -> &'static str))
}

/// Iterate over every word in order. O(1) to set up, no allocation.
#[inline]
pub fn iter() -> impl Iterator<Item = &'static str> + Clone {
    (0..LEN).map(word as fn(usize) -> &'static str)
}

/// Find a word's index. O(log n), no allocation. Not found is `None`.
///
/// The embedded list is sorted by byte order and duplicate-free, so this is a
/// binary search. Matching is exact and case-sensitive; every embedded word is
/// lowercase ASCII, so anything else is always `None`.
///
/// ```
/// let w = am_wordlist::get(100).unwrap();
/// assert_eq!(am_wordlist::position(w), Some(100));
/// assert_eq!(am_wordlist::position("Not A Word"), None);
/// ```
#[inline]
pub fn position(word: &str) -> Option<usize> {
    let i = partition_point(0, LEN, |i| self::word(i) < word);
    (i < LEN && self::word(i) == word).then_some(i)
}

/// Whether the list contains a word. O(log n), no allocation.
///
/// ```
/// assert!(am_wordlist::contains(am_wordlist::get(0).unwrap()));
/// assert!(!am_wordlist::contains("zzzzzzzz"));
/// ```
#[inline]
pub fn contains(word: &str) -> bool {
    position(word).is_some()
}

/// Iterate over every word starting with `prefix`, in order. O(log n) to set
/// up, no allocation.
///
/// An empty prefix yields the whole list; a prefix no word starts with yields
/// nothing.
///
/// ```
/// let mut it = am_wordlist::starting_with("aba");
/// assert!(it.all(|w| w.starts_with("aba")));
/// assert_eq!(am_wordlist::starting_with("zzzzzzzz").count(), 0);
/// ```
#[inline]
pub fn starting_with(prefix: &str) -> impl Iterator<Item = &'static str> + Clone {
    // Words sharing a prefix are contiguous in a sorted list: skip everything
    // ordered before the prefix, then take while the prefix still matches.
    let start = partition_point(0, LEN, |i| word(i) < prefix);
    let end = partition_point(start, LEN, |i| word(i).starts_with(prefix));
    (start..end).map(word as fn(usize) -> &'static str)
}

#[cfg(test)]
mod tests {

    /// Pins the byte-level shape of every word. An off-by-one in the span
    /// index would leak a separator byte into a word, or truncate one.
    #[test]
    fn every_word_is_clean_lowercase_ascii() {
        for (i, w) in super::iter().enumerate() {
            assert!(!w.is_empty(), "empty word at {i}");
            assert!(
                w.bytes().all(|b| b.is_ascii_lowercase()),
                "word {i} is not pure lowercase ascii: {w:?}"
            );
        }
    }

    #[test]
    fn position_round_trips_with_get() {
        // Sample across the list rather than walking all of it.
        for i in (0..super::len()).step_by(97) {
            let w = super::get(i).unwrap();
            assert_eq!(super::position(w), Some(i), "round trip failed for {w:?}");
        }
    }

    #[test]
    fn contains_agrees_with_linear_scan() {
        for probe in ["a", "zebra", "apple", "cackle", "abandon"] {
            let expected = super::iter().any(|w| w == probe);
            assert_eq!(
                super::contains(probe),
                expected,
                "disagreement on {probe:?}"
            );
        }
    }

    #[test]
    fn contains_rejects_non_words() {
        // Empty, uppercase and punctuated inputs can never be in the list.
        for probe in ["", "Apple", "not-a-word", "zzzzzzzz", "apple pie"] {
            assert!(!super::contains(probe), "should not contain {probe:?}");
            assert_eq!(super::position(probe), None);
        }
    }

    #[test]
    fn starting_with_matches_linear_filter() {
        for prefix in ["ab", "zy", "q", "cackl"] {
            let expected: usize = super::iter().filter(|w| w.starts_with(prefix)).count();
            let got = super::starting_with(prefix).count();
            assert_eq!(got, expected, "wrong count for prefix {prefix:?}");
            assert!(super::starting_with(prefix).all(|w| w.starts_with(prefix)));
        }
    }

    #[test]
    fn starting_with_edge_cases() {
        // Empty prefix matches everything; an impossible prefix matches nothing.
        assert_eq!(super::starting_with("").count(), super::len());
        assert_eq!(super::starting_with("zzzzzzzz").count(), 0);
        // A prefix that is itself a word includes that word.
        let w = super::get(0).unwrap();
        assert!(super::starting_with(w).any(|x| x == w));
    }

    #[test]
    fn sorted_and_unique() {
        let mut prev: Option<&str> = None;
        for (i, w) in super::iter().enumerate() {
            if let Some(p) = prev {
                assert!(p < w, "not sorted/unique at {i}: {p:?} then {w:?}");
            }
            prev = Some(w);
        }
    }
    #[test]
    fn non_empty() {
        assert!(super::len() > 0);
        assert_eq!(super::len(), super::LEN);
        assert!(!super::is_empty());
    }

    #[test]
    fn bounds() {
        assert!(super::get(0).is_some());
        assert!(super::get(super::len() - 1).is_some());
        assert!(super::get(super::len()).is_none());
        assert!(super::get(usize::MAX).is_none());
    }

    #[test]
    fn iter_matches_get() {
        assert_eq!(super::iter().count(), super::len());
        for (i, w) in super::iter().enumerate() {
            assert_eq!(super::get(i), Some(w));
        }
    }

    #[test]
    fn get_range_matches_get() {
        let mut range = super::get_range(2..5).unwrap();
        assert_eq!(range.clone().count(), 3);
        assert_eq!(range.next(), super::get(2));
        assert_eq!(range.next(), super::get(3));
        assert_eq!(range.next(), super::get(4));
        assert_eq!(range.next(), None);
    }

    #[test]
    fn get_range_bounds_variants() {
        let full = super::len();
        assert_eq!(super::get_range(..).unwrap().count(), full);
        assert_eq!(super::get_range(..3).unwrap().count(), 3);
        assert_eq!(super::get_range(0..=2).unwrap().count(), 3);
        assert_eq!(super::get_range(full - 1..).unwrap().count(), 1);
        // Empty ranges are valid and yield nothing.
        assert_eq!(super::get_range(2..2).unwrap().count(), 0);
    }

    #[test]
    fn get_range_out_of_bounds() {
        let full = super::len();
        assert!(super::get_range(0..=full).is_none());
        assert!(super::get_range(full + 1..full + 2).is_none());
        // start past end is rejected, not clamped.
        let (a, b) = (5usize, 2usize);
        assert!(super::get_range(a..b).is_none());
        assert!(super::get_range(..=usize::MAX).is_none());
    }
}
